<script lang="ts">
	import { onMount } from 'svelte';
	import { decode } from 'blurhash';

	/**
	 * The hash string generated by BlurHash.
	 * @type {string}
	 */
	export let hash = '';

	/**
	 * The width of the canvas.
	 * @type {number}
	 * @default 400
	 */
	export let width = 400;

	/**
	 * The height of the canvas.
	 * @type {number}
	 * @default 300
	 */
	export let height = 300;

	/**
	 * The punch value for enhancing the contrast.
	 * @type {number}
	 * @default 1
	 */
	export let punch = 1;

	let canvas: HTMLCanvasElement;

	onMount(() => {
		if (!hash) return;

		const pixels = decode(hash, width, height, punch);
		const ctx = canvas.getContext('2d');
		const imageData = ctx.createImageData(width, height);
		imageData.data.set(pixels);
		ctx.putImageData(imageData, 0, 0);
	});
</script>

<canvas bind:this={canvas} {width} {height}></canvas>

<style>
	canvas {
		display: block;
		width: 100%;
		height: auto;
	}
</style>
